### ISSUE TITLE
react-router 1.0.0

### ISSUE THREAD

**Issue by ColtonProvias** [insin/react-router-active-component#1]
react-router is now nearing 1.0.0 and 1.0.0-beta3 is currently on npm.  This may have to be updated due to the API changes that have happened.

**Comment by moimael** [comment]
Yep it doesnt work with react router 1.0.0-rc3 and react 0.14

**Comment by FlorianGoussin** [comment]
If I replace the React 13 by the version14 on the demo and I replaced the final lines in app.jsx

```
ReactRouter.run(...)
```

by 

```
ReactDOM.render(<ReactRouter>{routes}</ReactRouter>, document.getElementById('app'));
```

I get these errors:
    Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a     string (for DOM elements) or a ReactClass (for composite components).warning @ react.js:18780
react.js:18348 Uncaught Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.

![image](https://cloud.githubusercontent.com/assets/4402620/11490677/2db44134-9798-11e5-8014-4574c06edeb9.png)
